const TILE_SIZE: number = 64
const COL = 20
const ROW = 12
const GATE_POSITION_X = TILE_SIZE * (COL - 3)
const BLUE_GEM_POSITION = { x: 960, y: 54 }
const RED_GEM_POSITION = { x: 1068, y: 54 }
const YELLOW_GEM_POSITION = { x: 1176, y: 54 }
const BASE_HEALTH = 1000
const FPS = 60
export { BASE_HEALTH, FPS, GATE_POSITION_X, TILE_SIZE, ROW, BLUE_GEM_POSITION, YELLOW_GEM_POSITION, RED_GEM_POSITION }
